/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package utools.launchit.ui;

import static utools.launchit.LaunchItConstants.INPUT_ALIAS;
import utools.launchit.custom.CustomTextField;

/**
 *
 * @author ruinmaxk
 */
public class LaunchItAddNewMappingPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNewMappingPanel
     */
    public LaunchItAddNewMappingPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        customTextFieldComponent1 = new org.japo.java.swing.samples.CustomTextFieldComponent();
        customTextFieldComponent2 = new org.japo.java.swing.samples.CustomTextFieldComponent();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utools/launchit/res/icon_folder_small.png"))); // NOI18N

        customTextFieldComponent1.setHint("Alias");
        customTextFieldComponent1.setHintColor(java.awt.Color.gray);

        customTextFieldComponent2.setHint("Path to application");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customTextFieldComponent1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(customTextFieldComponent2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customTextFieldComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customTextFieldComponent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.japo.java.swing.samples.CustomTextFieldComponent customTextFieldComponent1;
    private org.japo.java.swing.samples.CustomTextFieldComponent customTextFieldComponent2;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
